ACCOUNT_ID=""
ENV_ID=""

VPC_ID=""
SECURITY_GROUPS=[""]
SUBNET_IDS=[""] # in AZ_ID
AZ_MODE="SINGLE"
AZ_ID="use1-az6"

S3_BUCKET=""

ENDPOINT_URL=None

# USER
KDB_USERNAME=""

# IAM Role
EXECUTION_ROLE=f"arn:aws:iam::{ACCOUNT_ID}:role/kdb-all-user"

# Access Variables
AWS_ACCESS_KEY_ID=None
AWS_SECRET_ACCESS_KEY=None
AWS_SESSION_TOKEN=None

AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_SESSION_TOKEN=""
